
# Keywords to check against scrapped data
SEskills_keywords = [
    "Python",
    "Java",
    "C++",
    "C#",
    "JavaScript",
    "HTML",
    "CSS",
    "SQL",
    "Git",
    "Docker",
    "Kubernetes",
    "RESTful",
    "APIs",
    "AWS",
    "Azure",
    "Google Cloud",
    "Linux",
    "Unix",
    "Shell Scripting",
    "Data Structures",
    "Algorithms",
    "Object-Oriented Programming",
    "Functional Programming",
    "Frontend Development",
    "Backend Development",
    "Web Development",
    "Mobile App Development",
    "Database Design",
    "NoSQL",
    "Microservices",
    "Agile Development",
    "Scrum",
    "Kanban",
    "Continuous Integration",
    "Continuous Deployment",
    "Test-Driven Development",
    "DevOps",
    "Software Architecture",
    "Design Patterns",
    "Code Review",
    "Unit Testing",
    "Debugging",
    "Performance Optimization",
    "User Experience (UX)",
    "User Interface (UI) Design",
    "Version Control",
    "Dependency Management",
    "Agile Methodologies",
    "Software Development Lifecycle",
    "Code Optimization",
    "Scalability",
    "Serverless Computing",
    "CI/CD",
    "AI",
    "Blockchain",
    "IoT",
    "Big Data",
    "Data Science",
    "Software Testing",
    "Automation Testing",
    "Containerization",
    "Scripting",
    "Microsoft Visual Studio",
    "Microsoft .NET framework",
    "UML",
    "ASIC flow layout design",
    "design to tape-out",
    "EDA tools",
    "NLP",
    "BERT",
    "GPT",
    "spaCy",
    "DOTNET",
    "SDLC",
    "GEM",
    "SECS",
    "system design",
    "Knowledge of programming",
    "OOP",
    ".NET",
    "cloud technologies",
    "servo",
    "motion control systems",
    "Unreal Engine",
    "Unity",
    "embedded software development",
    "quality control",
    "node.js"
]

ISecskills_keywords = [
    "Network Security",
    "Security Architecture",
    "Penetration Testing",
    "Vulnerability Assessment",
    "Vulnerability Assessments"
    "Incident Response",
    "Security Policies",
    "Risk Assessment",
    "Security Auditing",
    "Firewalls",
    "Intrusion Detection",
    "IDS",
    "Intrusion Prevention",
    "IPS",
    "Security Awareness",
    "Encryption",
    "Access Control",
    "Security Compliance",
    "Security Protocols",
    "Security Analysis",
    "Incident Management",
    "Security Operations",
    "Identity and Access Management",
    "IAM",
    "Information Security Manager",
    "Certified Ethical Hacker",
    "Information Systems Auditor",
    "Cloud Security Professional",
    "Security Tools",
    "Intrusion Detection and Prevention Systems",
    "IDPS",
    "Antivirus Software",
    "Network Monitoring",
    "Forensic Analysis",
    "Malware Analysis",
    "Data Loss Prevention",
    "DLP",
    "Security Patch Management",
    "Security Awareness Training",
    "Risk Management",
    "Secure Coding Practices",
    "Cloud Security",
    "Mobile Device Security",
    "Wireless Network Security",
    "Physical Security",
    "Disaster Recovery Planning",
    "Security Consulting",
    "Security Governance",
    "Security Metrics and KPIs",
    "Threat Intelligence",
    "Security Awareness Programs",
    "Security Best Practices",
    "Cybersecurity Frameworks",
    "Security Assessment",
    "Security Compliance",
    "Security Strategy",
    "CISM",
    "CISSP",
    "ISTQB",
    "Risk articulation",
    "Cloud technologies",
    "Data protection",
    "Cloud platforms",
    "CISA",
    "CCSP",
    "Security certifications",
    "CRISK",
    "CEH",
    "OSCP",
    "CCNA",
    "Secure Software Development Life Cycle",
    "SSDLC",
    "SIEM technologies",
    "Vulnerability Management",
    "Threat Intelligence",
    "IT frameworks",
    "GDPR",
    "COBIT",
    "ISO 27001",
    "NIST"
    "Log management",
    "IPS/IDS",
    "Anti-DDoS",
    "Data Leakage Prevention",
    "Proxy",
    "Automation & Orchestration",
    "AV",
    "CASB",
    "FW",
    "Ethical Hacking",
    "Forensics",
    "MITRE Framework",
    "NIST Framework",
    "Security by Design Framework",
    "SBD"
    "Vulnerability scanning",
    "Databases",
    "Data analytics",
    "Visualization",
    "Programming",
    "SSL",
    "VPN",
    "VPNs",
    "WAF",
    "APT",
    "OT/IOT Cybersecurity",
    "Active Directory",
    "DNS",
    "TCP/IP networking",
    "LAN/WAN setup and maintenance",
]

Q_keywords = [
    "Vocational",
    "Bachelor",
    "Master"
    "Doctoral",
    "PhD"
    "Certification",
    "Diploma"
]
